language: ruby
sudo: false
rvm:
- 2.3.3
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
script: ./script/cibuild
deploy:
  provider: script
  script: ./script/cideploy
  skip_cleanup: true
before_install:
- openssl aes-256-cbc -K $encrypted_5cb6ab5ef4f4_key -iv $encrypted_5cb6ab5ef4f4_iv
  -in script/deploy_id_rsa.enc -out deploy_id_rsa -d
