# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: MirageOS
email: anil@recoil.org
description: > # this means to ignore newlines until "baseurl:"
  MirageOS is a ...
baseurl: ""
url: "https://mirage.github.io/"

# Build settings
exclude:
  - Gemfile
  - Gemfile.lock

markdown: kramdown
kramdown:
  input: GFM

collections:
 authors:
 roles:
 papers:
 wiki:
  output: true

# used this for post_excerpt at index_page
excerpt_separator: <!--description-->
